### ISSUE TITLE
async-worker/daemon will timeout and throw exception when BRPOPLPUSH timeout

### ISSUE THREAD

**Issue by ihipop** [bazilio91/yii2-async#11]
when thereis no data in queue,BRPOPLPUSH is blocking and will timeout and throw exception when BRPOPLPUSH timeout 

```
Error: Failed to read from socket.
Redis command was: BRPOPLPUSH queue:xxx queue:xxx:progress 0
```

**Comment by bazilio91** [comment]
Please attach your redis connection config.

**Comment by ihipop** [comment]
``` php
'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'ip.redisserver',
            'port' => 6379,
            'database' => 0,
        ],
```

...

``` php
'async' => [
            'class' => 'bazilio\async\AsyncComponent',
            'transportClass' => 'bazilio\async\transports\AsyncRedisTransport',
            'transportConfig' => [
                'connection' => 'redis',
            ]
        ],
```

if there is data in queen,or the lack of data is in a short time period,everything is fine.
if there is a long time period that the queen is empty,BRPOPLPUSH  will timeout and throw exception

**Comment by bazilio91** [comment]
Try to add `'dataTimeout' => -1, // important for daemon and blocking queries` to redis config as described in docs.

**Comment by ihipop** [comment]
add `dataTimeout` will affect other  code that use the  thame redis connection.
i have to add two redis connection config  only different is the `dataTimeout`
maybe we can catch  and ignore the exception and restart the loop

**Comment by bazilio91** [comment]
You can extend command for your needs. I don't think that muting connection errors is a good idea.
