### ISSUE TITLE
Mysql provider support

### ISSUE THREAD

**Issue by bazilio91** [bazilio91/yii2-async#3]

**Comment by bazilio91** [comment]
I have no interest in this right now, but it should be easy to implement this transport.

**Comment by elviskudo** [comment]
hi, thanks for your work

i wanna ask, i have mysql connection here, so how can i connect with my db?
thanks for your attention and thanks again for your great work

**Comment by bazilio91** [comment]
Thanks! You can't connect to mysql server out of the box, there is no transport implemented for mysql by now. If you need that, you can create a transport that provides sql queues support.

**Comment by elviskudo** [comment]
ok thanks
by the way, do you have any recommendation for yii2 async with mysql support?
