### ISSUE TITLE
Breaking Windows compatibility

### ISSUE THREAD

**Issue by ydakilux** [bazilio91/yii2-async#9]
Hi,

 I just updated yii2-async,

  Now you are using the function pcntl_signal in AsyncWorkerCommand and this function is not compatible with Windows system.

  Until now it's compatible, if it's possible to continue with the compatibility.
   I temporarily disabled the call yo the pcntl_signal function, and seems it's working again.

**Comment by bazilio91** [comment]
Try to update again.

https://github.com/bazilio91/yii2-async/releases/tag/0.1.2

**Comment by ydakilux** [comment]
Great, it's working again.
    You can close the issue.

   Thanks a lot.
